-- MySQL Script generated by MySQL Workbench
-- lun 17 dic 2018 17:41:06 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE TYPE DNI AS (
numeros INTEGER,
letra VARCHAR(2));

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.Persona
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Persona (
  dni DNI NOT NULL,
  Nombre VARCHAR(45) NULL,
  Apellidos VARCHAR(45) NULL,
  Fecha_Nacimiento DATE NULL,
  PRIMARY KEY (DNI));


-- -----------------------------------------------------
-- Table mydb.Familia
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Familia (
  Cabeza_familia VARCHAR(9) NOT NULL,
  PRIMARY KEY (Cabeza_familia),
  CONSTRAINT fk_Familia_1
    FOREIGN KEY (Cabeza_familia)
    REFERENCES mydb.Persona (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table mydb.Calle
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Calle (
  Nombre_calle VARCHAR(45) NOT NULL,
  PRIMARY KEY (Nombre_calle))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Municipio
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Municipio (
  Nombre_municipio VARCHAR(45) NOT NULL,
  PRIMARY KEY (Nombre_municipio));


-- -----------------------------------------------------
-- Table mydb.Zona_urbana
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Zona_urbana (
  Nombre_zona VARCHAR(45) NOT NULL,
  PRIMARY KEY (Nombre_zona));


-- -----------------------------------------------------
-- Table mydb.Unifamiliar
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Unifamiliar (
  Nombre_municipio VARCHAR(45) NULL,
  Nombre_calle VARCHAR(45) NOT NULL,
  Nombre_zona VARCHAR(45) NULL,
  nº INT NOT NULL,
  PRIMARY KEY (nº),
  CONSTRAINT fk_Unifamiliar_1
    FOREIGN KEY (Nombre_calle)
    REFERENCES mydb.Calle (Nombre_calle)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Unifamiliar_2
    FOREIGN KEY (Nombre_municipio)
    REFERENCES mydb.Municipio (Nombre_municipio)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Unifamiliar_3
    FOREIGN KEY (Nombre_zona)
    REFERENCES mydb.Zona_urbana (Nombre_zona)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_Unifamiliar_1_idx ON mydb.Unifamiliar (Nombre_calle ASC);

CREATE INDEX fk_Unifamiliar_2_idx ON mydb.Unifamiliar (Nombre_municipio ASC);

CREATE INDEX fk_Unifamiliar_3_idx ON mydb.Unifamiliar (Nombre_zona ASC);


-- -----------------------------------------------------
-- Table mydb.Piso
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Piso (
  nº_bloque INT NOT NULL,
  nº_puerta INT NOT NULL,
  planta INT NOT NULL,
  Calle VARCHAR(45) NULL,
  Zona VARCHAR(45) NULL,
  Municipio VARCHAR(45) NULL,
  PRIMARY KEY (nº_bloque, nº_puerta, planta),
  CONSTRAINT fk_Piso_1
    FOREIGN KEY (Calle)
    REFERENCES mydb.Calle (Nombre_calle)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Piso_2
    FOREIGN KEY (Municipio)
    REFERENCES mydb.Municipio (Nombre_municipio)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Piso_3
    FOREIGN KEY (Zona)
    REFERENCES mydb.Zona_urbana (Nombre_zona)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_Piso_1_idx ON mydb.Piso (Calle ASC);

CREATE INDEX fk_Piso_2_idx ON mydb.Piso (Municipio ASC);

CREATE INDEX fk_Piso_3_idx ON mydb.Piso (Zona ASC);


-- -----------------------------------------------------
-- Table mydb.Propietario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Propietario (
  dni DNI NOT NULL,
  Nombre VARCHAR(45) NULL,
  Unifamiliar_nº INT NOT NULL,
  Piso_nº_bloque INT NOT NULL,
  Piso_nº_puerta INT NOT NULL,
  Piso_planta INT NOT NULL,
  PRIMARY KEY (DNI),
  CONSTRAINT fk_Propietario_1
    FOREIGN KEY (DNI)
    REFERENCES mydb.Persona (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Propietario_Unifamiliar1
    FOREIGN KEY (Unifamiliar_nº)
    REFERENCES mydb.Unifamiliar (nº)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Propietario_Piso1
    FOREIGN KEY (Piso_nº_bloque , Piso_nº_puerta , Piso_planta)
    REFERENCES mydb.Piso (nº_bloque , nº_puerta , planta)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_Propietario_Unifamiliar1_idx ON mydb.Propietario (Unifamiliar_nº ASC);

CREATE INDEX fk_Propietario_Piso1_idx ON mydb.Propietario (Piso_nº_bloque ASC, Piso_nº_puerta ASC, Piso_planta ASC);


-- -----------------------------------------------------
-- Table mydb.Bloque
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Bloque (
  nº INT NOT NULL,
  Calle VARCHAR(45) NULL,
  Zona VARCHAR(45) NULL,
  Municipio VARCHAR(45) NULL,
  m2_totales INT NULL,
  PRIMARY KEY (nº),
  CONSTRAINT fk_Bloque_1
    FOREIGN KEY (Calle)
    REFERENCES mydb.Calle (Nombre_calle)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Bloque_2
    FOREIGN KEY (Municipio)
    REFERENCES mydb.Municipio (Nombre_municipio)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Bloque_3
    FOREIGN KEY (Zona)
    REFERENCES mydb.Zona_urbana (Nombre_zona)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_Bloque_1_idx ON mydb.Bloque (Calle ASC);

CREATE INDEX fk_Bloque_2_idx ON mydb.Bloque (Municipio ASC);

CREATE INDEX fk_Bloque_3_idx ON mydb.Bloque (Zona ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

